[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Germain <germain.gau@gmail.com>"]

[dependencies]
num-complex = "0.1"
itertools = "0.7.7"
image = "0.23.12"
rayon = "1.0.1"
clap = {version = "2.31", features = ["yaml"]}
regex = "0.2"
indicatif = {version = "*", features = ["rayon"]}
